### ISSUE TITLE
BUG Report breaks with fulltextsearch module installed

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-externallinks#35]
When I run the report with the fulltextsearch module installed I get an exception at the end of the report run which stems from `FTS::flush_dirty_indexes()`.

Needs more investigation and to be fixed.

```
ERROR [UNKNOWN TYPE, ERRNO ]: Exception: HTML Parse Error: No current controller available in /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Indexes/SearchIndex.php:505
Stack trace:
#0 [internal function]: SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->SilverStripe\FullTextSearch\Search\Indexes\{closure}(512, 'No current cont...', '/Users/robbieav...', 547, Array)
#1 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Control/Controller.php(547): user_error('No current cont...', 512)
#2 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Security/BasicAuth.php(207): SilverStripe\Control\Controller::curr()
#3 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Control/Controller.php(102): SilverStripe\Security\BasicAuth::protect_site_if_necessary()
#4 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Control/Controller.php(122): SilverStripe\Control\Controller->init()
#5 /Users/robbieaverill/dev/ss4/vendor/dnadesign/silverstripe-elemental/src/Models/BaseElement.php(383): SilverStripe\Control\Controller->doInit()
#6 /Users/robbieaverill/dev/ss4/vendor/dnadesign/silverstripe-elemental/src/Models/ElementalArea.php(127): DNADesign\Elemental\Models\BaseElement->getController()
#7 [internal function]: DNADesign\Elemental\Models\ElementalArea->ElementControllers()
#8 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/ViewableData.php(477): call_user_func_array(Array, Array)
#9 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/ViewableData.php(524): SilverStripe\View\ViewableData->obj('ElementControll...', NULL, true)
#10 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/ORM/DataObject.php(3678): SilverStripe\View\ViewableData->hasValue('ElementControll...', NULL, true)
#11 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/SSViewer_Scope.php(323): SilverStripe\ORM\DataObject->hasValue('ElementControll...', NULL, true)
#12 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/SSViewer_DataPresenter.php(309): SilverStripe\View\SSViewer_Scope->__call('hasValue', Array)
#13 /private/var/tmp/silverstripe-cache-php7.0.22-Users-robbieaverill-dev-ss4/root/.cachevendor.dnadesign.silverstripe-elemental.templates.DNADesign.Elemental.Models.ElementalArea.ss(2): SilverStripe\View\SSViewer_DataPresenter->__call('hasValue', Array)
#14 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/SSViewer.php(597): include('/private/var/tm...')
#15 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/SSViewer.php(669): SilverStripe\View\SSViewer->includeGeneratedTemplate('/var/tmp//silve...', Object(DNADesign\Elemental\Models\ElementalArea), NULL, Array, NULL)
#16 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/View/ViewableData.php(393): SilverStripe\View\SSViewer->process(Object(DNADesign\Elemental\Models\ElementalArea), NULL)
#17 /Users/robbieaverill/dev/ss4/vendor/dnadesign/silverstripe-elemental/src/Models/ElementalArea.php(92): SilverStripe\View\ViewableData->renderWith(Object(SilverStripe\View\SSViewer))
#18 /Users/robbieaverill/dev/ss4/vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalPageExtension.php(42): DNADesign\Elemental\Models\ElementalArea->forTemplate()
#19 [internal function]: DNADesign\Elemental\Extensions\ElementalPageExtension->getElementsForSearch()
#20 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Core/Extensible.php(144): call_user_func_array(Array, Array)
#21 /Users/robbieaverill/dev/ss4/vendor/silverstripe/framework/src/Core/CustomMethods.php(61): SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(Object(Page), Array)
#22 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Indexes/SearchIndex.php(543): SilverStripe\View\ViewableData->__call('getElementsForS...', Array)
#23 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Solr/SolrIndex.php(520): SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->_getFieldValue(Object(Page), Array)
#24 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Solr/SolrIndex.php(582): SilverStripe\FullTextSearch\Solr\SolrIndex->_addField(Object(Apache_Solr_Document), Object(Page), Array)
#25 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Solr/SolrIndex.php(604): SilverStripe\FullTextSearch\Solr\SolrIndex->_addAs(Object(Page), 'SilverStripe\\CM...', Array)
#26 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Processors/SearchUpdateProcessor.php(90): SilverStripe\FullTextSearch\Solr\SolrIndex->add(Object(Page))
#27 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Processors/SearchUpdateProcessor.php(142): SilverStripe\FullTextSearch\Search\Processors\SearchUpdateProcessor->prepareIndexes()
#28 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Processors/SearchUpdateImmediateProcessor.php(9): SilverStripe\FullTextSearch\Search\Processors\SearchUpdateProcessor->process()
#29 /Users/robbieaverill/dev/ss4/vendor/silverstripe/fulltextsearch/code/Search/Updaters/SearchUpdater.php(210): SilverStripe\FullTextSearch\Search\Processors\SearchUpdateImmediateProcessor->triggerProcessing()
#30 [internal function]: SilverStripe\FullTextSearch\Search\Updaters\SearchUpdater::flush_dirty_indexes()
#31 {main}
```

**Comment by robbieaverill** [comment]
It might be worth leaving this issue until fulltextsearch is finished being upgraded

**Comment by robbieaverill** [comment]
Cannot reproduce anymore against fulltextsearch 2.0.0-beta1
